language: node_js
node_js:
  - "9"
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng build --prod
  - firebase use running-book
after_success:
  - firebase deploy --token $FIREBASE_TOKEN