language: node_js
node_js:
 - "9"
script:
 - echo "Deploy!!"
install:
 - npm install -g firebase-tools && ng build --prod
after_success:
 - firebase deploy --project running-book --token $FIREBASE_TOKEN